
import './globals.css';
import Head from 'next/head';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>My Website Title</title> {/* Page title */}
        <meta name="description" content="A brief description of my website" /> {/* Meta description */}
        <link rel="icon" href="/favicon.ico" /> {/* Favicon */}
      </Head>
      <body>{children}</body>
    </html>
  )
}
